### PR TITLE
Do not let multiple reports run at the same time, due to memory/connecti...

### PR DESCRIPTION
**Pull request by AaronCMuller**
...on issues.

### CODE REVIEW

**Comment by AaronCMuller** [comment]
@JonathanShaw Thoughts?

**Comment by scoen** [comment]
won't that just prevent the same report being run concurrently ?

**Comment by AaronCMuller** [comment]
@scoen Yes, but this was intended to disallow multiple of the same type of report to run at the same time, not any report at all. I was tossing up between the two.

**Comment by scoen** [comment]
Fair enough. I expect it should do the trick then.

Note: A second call to run the report (while another is already running) may hang until a page timeout or otherwise throw an error – I’m unsure what the outcome is under spring & jetty.

Might be worth experimenting (maybe not?).

**Pull request merged**
